### ISSUE TITLE
Doubt in "QCAE"

### ISSUE THREAD

**Issue by Dxplosion** [Orkis-Research/Pytorch-Quaternion-Neural-Networks#10]
Hi,
I was trying to running “cae.py” in QCAE mode but experienced error

"Traceback (most recent call last):
  File "E:/PyCharm Community Edition 2018.3.5/PRO/Pytorch-Quaternion-Neural-Networks-master/cae.py", line 33, in <module>
    net = QCAE()
  File "E:\PyCharm Community Edition 2018.3.5\PRO\Pytorch-Quaternion-Neural-Networks-master\convolutional_models.py", line 33, in __init__
    self.e1 = QuaternionConv(4, 32, kernel_size=3, stride=2, padding=1)
  File "E:\PyCharm Community Edition 2018.3.5\PRO\Pytorch-Quaternion-Neural-Networks-master\quaternion_layers.py", line 127, in __init__
    self.r_weight  = Parameter(torch.Tensor(*self.w_shape))
TypeError: 'tuple' object cannot be interpreted as an integer"

I think maybe my versions of Python and Pytorch are not suitable so I want to know what versions of Python and Pytorch are you using and whether the code are needed to be modified?

Thank you,
Best,
Xu

**Comment by TParcollet** [comment]
Hi, interesting. I suppose it was pytorch 1.0.0 or something like this. I have to check what must be done.

**Comment by Dxplosion** [comment]
Thanks for reply. I have also tried pytorch 1.0.0 and there is still the same error. According to the error messages, the error happens because "self.w_shape" is a tuple whose pos 3 is not a int. In the default mode, "self.w_shape" is a tuple with shape of (8, 1, (3, 3)) and this results in failure in converting tuple to Tensor.
